pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk add --no-cache wget make g++ fuse-dev tar
      - wget --no-check-certificate http://www.rarlab.com/rar/unrarsrc-5.5.8.tar.gz
      - tar zxvf unrarsrc-5.5.8.tar.gz
      - cd unrar
      - make install
      - make lib
      - make install-lib
