pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk add --no-cache wget make g++ fuse-dev tar
      - wget --no-check-certificate http://www.rarlab.com/rar/unrarsrc-5.5.8.tar.gz
      - tar zxvf unrarsrc-5.5.8.tar.gz
      - cd unrar
      - make
      - make install
      - make lib
      - make install-lib
      - cd ..
      - wget --no-check-certificate https://github.com/hasse69/rar2fs/releases/download/v1.26.0/rar2fs-1.26.0.tar.gz
      - tar xvf rar2fs-1.26.0.tar.gz
      - cd rar2fs-1.26.0
      - ./configure --with-unrar=../unrar --with-unrar-lib=/usr/lib/
      - make
      - ls
      
  test:
    commands:
      - ./rar2fs
